### ISSUE TITLE
System clipboard out of the box?

### ISSUE THREAD

**Issue by csaez** [hotgloupi/nvim#1]
Hi there,

First of all, thanks so much for doing this, I've been using neovim in a centos6.6 box at work since I saw this on reddit and it works really well, it's so nice to finally move on from vim 7.2 on controlled environments where having root access is simply out of the table.

The only bit I'm missing so far is having access to system clipboard. Do you think it is possible to bundle xclip with the project?

Thanks!

**Comment by hotgloupi** [comment]
Thanks for using it !

I think it's a good idea since the clipboard functionality is really tied to the editor. If you want to give it a try, I would gladly accept a pull request :)

You just need to add the sources in the repository (gitmodule if xclip is on github, or just the sources), then add the build commands (like ./configure; make; make install) in the build.sh script.

Cheers,

**Comment by hotgloupi** [comment]
In fact, I'm looking at xsel (which seems to be newer, better and stronger). But I still think it's worth adding xclip so that we can have the option of choosing one or another :)
Let me know what you think !

**Comment by csaez** [comment]
I would say the difference is not huge from an user point of view, let's just pick one (xsel makes perfect sense) and try to make system clipboard work out of the box :)

**Comment by hotgloupi** [comment]
Just pushed a new release with it, would you be so kind to give it a try ? It's here:

https://github.com/hotgloupi/nvim/releases/download/0.6/nvim-linux.x86_64.tgz

If it's working, then I think we can close this issue :)

**Comment by csaez** [comment]
It works perfectly! 
Thanks so much :beer:

**Comment by csaez** [comment]
After more testing I realized that even though xsel is available on a teminal (i.e. `xsel --version`) neovim is not detecting it (`echo executable('xsel')`).

To workaround this, I'm using the following mappings to interact with xsel directly:
```
" system clipboard
map <Leader>yy :write !xsel -i -b<CR>
map <Leader>pp :read !xsel -b<CR>
```

**Comment by hotgloupi** [comment]
Thanks for investigating the issue ! Do you think I should integrate that ?
There's the launcher script that could export the absolute path (as done
for clang-format) and the sysinit.vim where I could add those command. I'm
not sure whether or not it's a good idea to do so though ...

**Comment by hotgloupi** [comment]
Quick question: is the binary directory that contains nvim and xsel in your
PATH ?

**Comment by csaez** [comment]
Hi,

Yes, the bin folder is the first in `$PATH` (I had to update the shebangs on most python scripts as they were pointing to the binaries on your local machine). That's the only reason why I can run `xsel --version` on a terminal just fine.

You can try it yourself by running `:echo executable("xsel")` within neovim, it should return 1 but it returns 0 using this portable version (`$SCREEN` is properly set and I have X11 installed, I'm testing it on a workstation running CentOS 6.6 + gnome classic).

About including the configuration by default: I wouldn't go that far, it seems a very opinionated approach that works good enough for me but it might not work for other people, if anything I would update the README so people is aware of the workaround (most vim users are comfortable editing dotfiles).

Cheers!
C.

**Comment by csaez** [comment]
Hi there,

It has been a while, but I wanted to let you know that xsel seems to finally work on https://github.com/hotgloupi/nvim/releases/tag/0.7 (after symlinking xsel into bin or added to PATH, just like you did with nvim) :)

Will keep testing things, but the latest release seems solid! Python3 seems to finally work, no more fixing hardcoded paths on python scripts (used to be the case with pip and other scripts shipped within the bin directory) and in general everything seems to work out of the box as intended.

Thanks for the good work! :+1:

**Comment by hotgloupi** [comment]
Thx for your feedback! I'm still not sure about the fact that only nvim is
exposed in the bin directory, maybe I should add xsel and call it a day ...
Also, there is still issue with clang-format and apparently, building with
gcc4.8 might cause issues with ctags...
All in all, I might do another release soon :)

Cheers!
